dependencies:
  - watermark==2.1.0
  - dataframe_image==0.1.1
  - numpy==1.19.2
  - matplotlib==3.3.2
  - geopy==2.1.0
  - pandas==1.1.3
  - osmnx==1.1.1
  - Cartopy==0.18.0
  - tqdm==4.62.0
  - networkx==2.5
